### ISSUE TITLE
Strange behavior with power button on GPD Win 4

### ISSUE THREAD

**Issue by ghost** [ShadowBlip/HandyGCCS#88]
Just noticed strange behavior regarding the power button. 

When handycon is started, the power button is intermittent, requiring multiple presses to enter the power menu.
When handycon is stopped, the power button works as intended, only requiring one press to enter the power menu.

I don't think this is intended.

**Comment by pastaq** [comment]
Thank you for reporting this. I think the Win4 might be unique, in that it uses a different power button device than most of these devices do so the event is getting lost. There is a part of the code that stops multiple events from firing on multiple power button uinput devices, which causes infinite sleep loops on other devices. Because of that I can't revert it without having a worse issue on those other devices. I'm working on a full refactor of HandyGCCS right now that will solve this issue by allowing me to more easily identify the primary power device per handheld, as well as a host of other improvements.

**Comment by pastaq** [comment]
Does this still happen in the latest version?

**Comment by ghosting3175** [comment]
The power button works but automatically sleeps the device instead of opening the standby menu which is the intended use.

**Comment by pastaq** [comment]
> The power button works but automatically sleeps the device instead of opening the standby menu which is the intended use.
Is this on the desktop? The power button has never been intended to bring up the power menu by default. If you're in steam you can change the config file to say shutdown instead of sleep and it will open the steam power menu that way.

**Comment by ghosting3175** [comment]
>Is this on the desktop?

Yes, I don't use front ends, I test this by booting in to KDE and then hit the power button.

**Comment by ghosting3175** [comment]
Then how are users meant to have working gyro on their handheld PC?

I want to have working gyro controls.

**Comment by pastaq** [comment]
Gyro was removed From the latest version due to issues with the implementation. It will be added back at a later time once it works with a universal interface.
